#!/bin/bash

set -e

# Font configuration
# Format: "TTF_FILENAME:OUTPUT_NAME:SIZE1,SIZE2,SIZE3,..."
# TTF_FILENAME: Name of the TTF file in fonts/ directory (without .ttf extension)
# OUTPUT_NAME: Base name for output file (e.g., "roboto_light" will generate "roboto_light_22.c")
# SIZES: Comma-separated list of font sizes to generate

FONT_CONFIGS=(
    "Roboto-Light:roboto_light:22,24,26,28,32,48"
    "Roboto-Regular:roboto_regular:22,24,26,28,32,48"
    "Roboto-Medium:roboto_medium:22,24,26,28,32,48"
    "Roboto-Bold:roboto_bold:22,24,26,28,32,48,50"
)

# Output directory
OUTPUT_DIR="../main/fonts"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FONT_DIR="${SCRIPT_DIR}"

# Character ranges to include
CHAR_RANGES=(
    "-r" "0x0020-0x007F"  # ASCII
    "-r" "0x00A0-0x00FF"  # Latin-1 Supplement
    "-r" "0x0100-0x017F"  # Latin Extended-A (for polish)
)

# LVGL font conversion options
LVGL_OPTIONS=(
    "--bpp" "4"
    "--no-compress"
    "--no-prefilter"
    "--force-fast-kern-format"
    "--format" "lvgl"
    "--lv-include" "lvgl.h"
)

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "========================================="
echo "LVGL Font Generator for Calaos Remote UI"
echo "========================================="
echo ""

# Check if lv_font_conv is installed
if ! command -v lv_font_conv &> /dev/null
then
    echo -e "${RED}ERROR: lv_font_conv is not installed${NC}"
    echo ""
    echo "Please install it using npm:"
    echo "  npm install -g lv_font_conv"
    echo ""
    exit 1
fi

# Create output directory if it doesn't exist
mkdir -p "${SCRIPT_DIR}/${OUTPUT_DIR}"

# Statistics
TOTAL_FONTS=0
GENERATED_FONTS=0
FAILED_FONTS=0

# Array to store generated font files for CMake
GENERATED_FILES=()

# Process each font configuration
for config in "${FONT_CONFIGS[@]}"
do
    IFS=':' read -r ttf_name output_name sizes <<< "$config"

    # Split sizes by comma
    IFS=',' read -ra SIZE_ARRAY <<< "$sizes"

    echo -e "${YELLOW}Processing font: ${ttf_name}${NC}"

    # Check if TTF file exists
    TTF_FILE="${FONT_DIR}/${ttf_name}.ttf"
    if [ ! -f "${TTF_FILE}" ]
    then
        echo -e "${RED}  ERROR: Font file not found: ${TTF_FILE}${NC}"
        FAILED_FONTS=$((FAILED_FONTS + ${#SIZE_ARRAY[@]}))
        TOTAL_FONTS=$((TOTAL_FONTS + ${#SIZE_ARRAY[@]}))
        continue
    fi

    # Generate font for each size
    for size in "${SIZE_ARRAY[@]}"
    do
        TOTAL_FONTS=$((TOTAL_FONTS + 1))
        OUTPUT_FILE="${SCRIPT_DIR}/${OUTPUT_DIR}/${output_name}_${size}.c"

        echo "  Generating ${output_name}_${size}.c (size: ${size}px)..."

        # Build lv_font_conv command
        if lv_font_conv \
            --size "${size}" \
            -o "${OUTPUT_FILE}" \
            "${LVGL_OPTIONS[@]}" \
            --font "${TTF_FILE}" \
            "${CHAR_RANGES[@]}" \
            2>&1
        then
            echo -e "  ${GREEN}✓ Successfully generated ${output_name}_${size}.c${NC}"
            GENERATED_FONTS=$((GENERATED_FONTS + 1))
            GENERATED_FILES+=("main/fonts/${output_name}_${size}.c")
        else
            echo -e "  ${RED}✗ Failed to generate ${output_name}_${size}.c${NC}"
            FAILED_FONTS=$((FAILED_FONTS + 1))
        fi
    done

    echo ""
done

# Summary
echo "========================================="
echo "Generation Summary"
echo "========================================="
echo "Total fonts to generate: ${TOTAL_FONTS}"
echo -e "${GREEN}Successfully generated: ${GENERATED_FONTS}${NC}"
if [ ${FAILED_FONTS} -gt 0 ]
then
    echo -e "${RED}Failed: ${FAILED_FONTS}${NC}"
fi
echo ""

if [ ${GENERATED_FONTS} -gt 0 ]
then
    # Generate CMake file
    CMAKE_FILE="${SCRIPT_DIR}/${OUTPUT_DIR}/fonts.cmake"
    echo "# Auto-generated CMake file for LVGL fonts" > "${CMAKE_FILE}"
    echo "# Generated by fonts/generate.sh" >> "${CMAKE_FILE}"
    echo "" >> "${CMAKE_FILE}"
    echo "set(FONT_SOURCES" >> "${CMAKE_FILE}"
    for font_file in "${GENERATED_FILES[@]}"
    do
        echo "    ${font_file}" >> "${CMAKE_FILE}"
    done
    echo ")" >> "${CMAKE_FILE}"
    echo "" >> "${CMAKE_FILE}"
    echo -e "${GREEN}✓ Generated CMake file: ${CMAKE_FILE}${NC}"
    echo ""

    echo -e "${YELLOW}NEXT STEPS:${NC}"
    echo "1. Add the following declarations to main/lv_conf.h in LV_FONT_CUSTOM_DECLARE section:"
    echo ""

    for config in "${FONT_CONFIGS[@]}"
    do
        IFS=':' read -r ttf_name output_name sizes <<< "$config"
        IFS=',' read -ra SIZE_ARRAY <<< "$sizes"

        for size in "${SIZE_ARRAY[@]}"
        do
            echo "   LV_FONT_DECLARE(${output_name}_${size}) \\"
        done
    done

    echo ""
    echo "2. Use fonts in your code like: lv_obj_set_style_text_font(obj, &${output_name}_22, 0);"
    echo ""
fi

if [ ${FAILED_FONTS} -eq 0 ] && [ ${GENERATED_FONTS} -gt 0 ]
then
    echo -e "${GREEN}All fonts generated successfully!${NC}"
    exit 0
else
    exit 1
fi
