# Auto-generated CMake file for LVGL fonts
# Generated by fonts/generate.sh

set(FONT_SOURCES
    main/fonts/roboto_light_22.c
    main/fonts/roboto_light_24.c
    main/fonts/roboto_light_26.c
    main/fonts/roboto_light_28.c
    main/fonts/roboto_light_32.c
    main/fonts/roboto_light_48.c
    main/fonts/roboto_regular_22.c
    main/fonts/roboto_regular_24.c
    main/fonts/roboto_regular_26.c
    main/fonts/roboto_regular_28.c
    main/fonts/roboto_regular_32.c
    main/fonts/roboto_regular_48.c
    main/fonts/roboto_medium_22.c
    main/fonts/roboto_medium_24.c
    main/fonts/roboto_medium_26.c
    main/fonts/roboto_medium_28.c
    main/fonts/roboto_medium_32.c
    main/fonts/roboto_medium_48.c
    main/fonts/roboto_bold_22.c
    main/fonts/roboto_bold_24.c
    main/fonts/roboto_bold_26.c
    main/fonts/roboto_bold_28.c
    main/fonts/roboto_bold_32.c
    main/fonts/roboto_bold_48.c
    main/fonts/roboto_bold_50.c
)

